bin.includes = META-INF/,\
               plugin.xml,\
               concepts/,\
               getting_started/,\
               reference/,\
               tasks/,\
               toc.xml,\
               topics_Concepts.xml,\
               topics_Getting_Started.xml,\
               topics_Reference.xml,\
               topics_Tasks.xml,\
               help.css,\
               images/,\
               context_help.xml
